notPseudonym Transformer update
statisticsnorway/microdata-job-executor pull request #20
Opened 2022-10-26 11:09 UTC by DanielElisenberg

# notPseudonym field transformer update

Updated the metadata model and transformer according to resolved discussion on gitlab.

### What's changed?
* notPseudonym field moved from keyType to variable
* transformer update for new model
* updated all testdata

2022-10-26 11:40 UTC, vaskalan requested changes
Can't find any unit tests verifying that notPseudonym is transformed correctly.
Correct me if I'm wrong.

2022-10-26 12:08 UTC, vaskalan commented on tests/resources/worker/steps/transformer/expected/KREFTREG_DS_enumerated.json
>        "variableRole": "Identifier",
True, but where are the unit tests located?

2022-10-26 12:11 UTC, DanielElisenberg commented on tests/resources/worker/steps/transformer/expected/KREFTREG_DS_enumerated.json
>        "variableRole": "Identifier",
* [transformer tests](https://github.com/statisticsnorway/microdata-job-executor/blob/master/tests/unit/worker/steps/test_dataset_transformer.py)
* [build metadata test](https://github.com/statisticsnorway/microdata-job-executor/blob/master/tests/unit/worker/test_build_metadata_worker.py)

2022-10-27 09:26 UTC, vaskalan commented on tests/resources/worker/steps/transformer/expected/KREFTREG_DS_enumerated.json
>        "variableRole": "Identifier",
Thank you, and sorry for the delay 😃

2022-10-27 09:26 UTC, vaskalan approved these changes

2022-10-27 09:37 UTC, merged